FROM python:3.11-slim
WORKDIR /code
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY ./src ./src
EXPOSE 8050
WORKDIR /code/src
ENTRYPOINT ["gunicorn", "--bind", "0.0.0.0:8050", "app:server"]